### ISSUE TITLE
FIX ATTRIBUTIon

### ISSUE THREAD

**Issue by Tonnieboy300** [Tonnieboy300/tonnieboy.com#18]
AHHHHHHHH

**Comment by Fenwit** [comment]
relatable

**Comment by Tonnieboy300** [comment]
The attribution page is not linked, and the license is not linked on that page

**Comment by Tonnieboy300** [comment]
On index.html, the attribution page is incorrectly linked to attribution.html, should be ./attribution

**Comment by Tonnieboy300** [comment]
On attribution/index.html, the link to the license should go to root
